version: '3.9'

services:
  smarthub:
    container_name: smarthub
    build:
      context: .
      dockerfile: ./apps/smarthub/Dockerfile
    ports:
      - '3001:3001'
    volumes:
      - .:/app/
    working_dir: /app/
    restart: on-failure
    networks:
      - smarthub-network

networks:
  smarthub-network:
    driver: bridge
