version: '3.9'

services:
  smarthub:
    container_name: smarthub
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
      - '3001:3001'
      - '3002:3002'
    volumes:
      - ./:/app/
      - /app/node_modules/
    working_dir: /app/
    restart: on-failure
    networks:
      - smarthub-network

networks:
  smarthub-network:
    driver: bridge
