version: '3.9'

services:
  cold-start:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.cold-start.build
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules