services:
  # nats-container:
  #   image: nats
  #   ports:
  #     - "4222:4222"
  # db:
  #   image: mysql:8.0.30-debian
  #   ports:
  #     - 3306:3306
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=root
  #     - MYSQL_DATABASE=my-db
  
  service-order-ms:
    container_name: service-order-ms
    build: ./apps/sot-backend/service-order
    volumes:
      - ./apps/sot-backend/service-order/src:/usr/src/app/src
    command: npm run start:dev
    
