version: '3.9'

services:
  cold-start:
    container_name: cold-start
    build:
      context: .
      dockerfile: ./apps/cold-start/Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/app/
    working_dir: /app/
    restart: on-failure
    command: npm start
    networks:
      - smarthub-network

networks:
  smarthub-network:
    driver: bridge
