version: "3.9"

services:
  web-coldstart:
    container_name: web-coldstart
    build:
      context: .
      dockerfile: ./apps/cold-start/Dockerfile.build
    restart: always
    ports:
      - 3000:3000

  web-smarthub:
    container_name: web-smarthub
    build:
      context: .
      dockerfile: ./apps/smarthub/Dockerfile.build
    restart: always
    ports:
      - 3001:3000
    
    volumes:
      -
  #   networks:
  #     - app_network
  # api:
  #   container_name: api
  #   build:
  #     context: .
  #     dockerfile: ./apps/api/Dockerfile
  #   restart: always
  #   ports:
  #     - 3001:3001
  #   networks:
  #     - app_network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
# networks:
#   app_network:
#     external: true