FROM node:20.2-alpine3.17 as base

FROM base AS pruned
RUN apk add --no-cache libc6-compat
RUN apk update
WORKDIR /app

RUN npm install -g turbo

COPY . .

RUN turbo prune --scope=cold-start --docker

#############################################
FROM base AS installer
WORKDIR /app

COPY --from=pruned /app/out/json/ .
COPY --from=pruned /app/out/package-lock.json /app/package-lock.json

# Forces the layer to recreate if the app's package.json changes
COPY apps/cold-start/package.json /app/apps/cold-start/package.json

COPY --from=pruned /app/out/full/ .
COPY turbo.json turbo.json

RUN turbo run build --no-cache --filter=cold-start

#############################################
FROM base AS runner
WORKDIR /app

COPY --from=installer /app .

CMD npm run dev