FROM node:20-alpine AS base


WORKDIR /app
RUN npm install -g turbo
COPY . .

FROM base AS installer
RUN apk add --no-cache libc6-compat
RUN apk update
WORKDIR /app

RUN npm ci
 
RUN npx turbo run dev --filter=smarthub
 
FROM base AS runner
WORKDIR /app
 
# Don't run production as root
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 angelo
USER angelo
 
COPY --from=installer /app/apps/smarthub/next.config.js .
COPY --from=installer /app/apps/smarthub/package.json .
 
# Automatically leverage output traces to reduce image size
# https://nextjs.org/docs/advanced-features/output-file-tracing
COPY --from=installer --chown=nextjs:nodejs /app/apps/smarthub ./
EXPOSE 3001

CMD ["npm", "run", "dev"]