import { Header } from "@smarthub/ui";
import SideMenu from "./components/SideMenu";
import "./globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";

const poppins = Poppins({
  preload: false,
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Cold Start",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en" className="h-full">
      <body className={`bg-white ${poppins} h-full`}>
        <Header app_name="COLD START" />
        <div className="flex h-[90%] sm:h-[87%]">
          <SideMenu />
          <main className="flex-1 min-h-screen">{children}</main>
        </div>
      </body>
    </html>
  );
}
