import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@smarthub/ui/src/globals.css";
import { ThemeProvider } from "@smarthub/ui";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Smarthub",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider defaultTheme="system" enableSystem attribute="class">
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
