import type { Metadata } from "next";
import { bosch_sans_global } from "@smarthub/fonts";
import { ThemeProvider } from "@smarthub/ui";
import "@smarthub/ui/src/globals.css";

export const metadata: Metadata = {
  title: "Smarthub",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en" suppressHydrationWarning className="h-full">
      <body className={`${bosch_sans_global.className} h-full`}>
        <ThemeProvider defaultTheme="system" attribute="class">
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
